### ISSUE TITLE
outputs\kotlin\ir 文件夹没有自动创建

### ISSUE THREAD

**Issue by loliball** [bennyhuo/kotlin-ir-printer#1]
java.lang.IllegalStateException: Directory does not exist: D:\AndroidApplication\MyApp\app\build\outputs\kotlin\ir
	at org.jetbrains.kotlin.incremental.FileUtilsKt.deleteDirectoryContents(fileUtils.kt:40)
	at com.bennyhuo.kotlin.ir.printer.compiler.IrSourcePrinterExtension.generate(IrPrinterIrGenerationExtension.kt:28)

**Comment by bennyhuo** [comment]
哦可以先用1.9.20-1.0.0，你说的问题是1.0.1引入的，为了修源码文件被删而结果没删的问题。我回头处理下。
