### ISSUE TITLE
IR lowering failed

### ISSUE THREAD

**Issue by loliball** [bennyhuo/kotlin-ir-printer#2]
irPrinter {
    isEnabled = true
    indent = "    "
    outputType = OutputType.KOTLIN_LIKE_JETPACK_COMPOSE_STYLE
}
```
java.lang.Exception: IR lowering failed at: LyricBean.kt
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitFile(JcIrSourcePrinter.kt:1541)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitFile(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitFile(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:31)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinterKt.dumpSrc(JcIrSourcePrinter.kt:125)
	at com.bennyhuo.kotlin.ir.printer.compiler.IrSourcePrinterExtension.generate(IrPrinterIrGenerationExtension.kt:36)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:225)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:463)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:477)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:400)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:281)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:125)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:657)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:105)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1624)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Unhandled operator dataClassArrayMemberToString
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitCall(JcIrSourcePrinter.kt:348)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:299)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitCall(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitCall(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.print(JcIrSourcePrinter.kt:148)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitStringConcatenation(JcIrSourcePrinter.kt:674)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitStringConcatenation(IrElementVisitorVoid.kt:452)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitStringConcatenation(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitStringConcatenation(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.expressions.IrStringConcatenation.accept(IrStringConcatenation.kt:24)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.print(JcIrSourcePrinter.kt:148)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitReturn(JcIrSourcePrinter.kt:809)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitReturn(IrElementVisitorVoid.kt:447)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitReturn(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitReturn(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.accept(IrReturn.kt:26)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.print(JcIrSourcePrinter.kt:148)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.printJoin(JcIrSourcePrinter.kt:171)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitBlockBody(JcIrSourcePrinter.kt:1063)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:216)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitBlockBody(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitBlockBody(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.print(JcIrSourcePrinter.kt:148)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.printBody(JcIrSourcePrinter.kt:265)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitSimpleFunction(JcIrSourcePrinter.kt:256)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:173)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitSimpleFunction(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitSimpleFunction(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:37)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.print(JcIrSourcePrinter.kt:148)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.printJoin(JcIrSourcePrinter.kt:171)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitClass(JcIrSourcePrinter.kt:1141)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:111)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitClass(JcIrSourcePrinter.kt:141)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitClass(JcIrSourcePrinter.kt:141)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.print(JcIrSourcePrinter.kt:148)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.printJoin(JcIrSourcePrinter.kt:171)
	at com.bennyhuo.kotlin.ir.printer.compiler.output.JcIrSourcePrinter.visitFile(JcIrSourcePrinter.kt:192)
	... 44 more
```
可能是反编译器有点问题，KOTLIN_LIKE，RAW_IR没问题可以正常生成
我的代码 `LyricBean.kt`
``` kotlin
package com.cnl.kikoeru.data.bean

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.cnl.kikoeru.utils.newString
import java.nio.charset.Charset

@Entity
data class LyricBean(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val rj: Long,                   // 12345 逐步弃用
    @ColumnInfo(defaultValue = "")
    val sourceId: String,           // RJxx BJxx VJxx
    val nameBin: ByteArray,
    var nameEnc: String? = null,
    val lyricBin: ByteArray,
    var lyricEnc: String? = null,
    val duration: Long = 0,
    val documentUri: String,        // content://xxx
    @ColumnInfo(defaultValue = "")
    val zipInnerPath: String = ""   // /a/b/xxx.zip \n /c/d/e.lrc
) {
    val name by lazy {
        nameBin.newString(Charset.forName(nameEnc ?: Charsets.UTF_8.name()))
            .substringAfterLast('/')
    }
    val lyric by lazy { lyricBin.newString(Charset.forName(lyricEnc ?: Charsets.UTF_8.name())) }
}
```

**Comment by bennyhuo** [comment]
好的，有空了我看一下这个case

**Comment by loliball** [comment]
``` kotlin
data class MyBean(val a: ByteArray)
```
最小复现代码，和room应该没关系  
似乎KOTLIN_LIKE_JETPACK_COMPOSE_STYLE不能很好的处理data class中的Array<*>类型

**Comment by bennyhuo** [comment]
> ``` kotlin
> data class MyBean(val a: ByteArray)
> ```
> 最小复现代码，和room应该没关系  
> 似乎KOTLIN_LIKE_JETPACK_COMPOSE_STYLE不能很好的处理data class中的Array<*>类型

对的，没有提供实现。回头我补一下。他们最新的代码也没有提供。。。。

**Comment by bennyhuo** [comment]
Fixed in 1.9.20-1.0.2.
